export default {
  ADD_USER: 'ADD_USER',
  ADD_USER_ERROR: 'ADD_USER_ERROR',
  CLEAN_REGISTER_STATUS: 'CLEAN_REGISTER_STATUS',
  CLEAN_LOGIN_STATUS: 'CLEAN_LOGIN_STATUS',
  LOGIN_USER: 'LOGIN_USER',
  LOGIN_ERROR: 'LOGIN_ERROR',
  UPLOAD_PRODUCT: 'UPLOAD_PRODUCT',
  CLEAN_UPLOAD_PRODUCT: 'CLEAN_UPLOAD_PRODUCT',
  GET_ALL_PRODUCTS: 'GET_ALL_PRODUCTS',
  GET_ALL_PRODUCTS_ERROR: 'GET_ALL_PRODUCTS_ERROR',
  FILTER_PRODUCTS: 'FILTER_PRODUCTS',
  CLEAN_FILTERS: 'CLEAN_FILTERS',
  UPDATE_PROFILE: 'UPDATE_PROFILE',
  DELETE_PRODUCT: 'DELETE_PRODUCT',
  LOG_OUT: 'LOG_OUT'
}
